---
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  # A bit ugly... See
  # https://github.com/ansible-community/ansible-lint/issues/1387
  # https://github.com/ansible-community/ansible-lint/pull/1490
  # even if merged, no resolution for external roles deps at the moment.
  ANSIBLE_ROLES_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/roles ansible-lint --exclude ${MOLECULE_EPHEMERAL_DIRECTORY}/roles -c .ansible-lint.yml ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu2004}
    dockerfile: ../docker/Dockerfile-${MOLECULE_DISTRO:-ubuntu2004}
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    sudo: true
